### ISSUE TITLE
UC_AI_TOOLS_API Invalid after upgrading to 25.5

### ISSUE THREAD

**Issue by vtnmolloy** [United-Codes/uc_ai#18]
After upgrading to 25.5 UC_AI_TOOLS_API was invalid with the following errors 

Package Body APPS.UC_AI_TOOLS_API@APPS@JERSEY4

Error(467,7): PL/SQL: SQL Statement ignored
Error(470,15): PL/SQL: ORA-00920: invalid relational operator

 `<<fetch_tools>>
    for rec in (
      select id
        from uc_ai_tools
       where (
              not l_enable_tool_filter
               or id in (
                 select tt.tool_id
                   from uc_ai_tool_tags tt
                  where tt.tag_name member of uc_ai.g_tool_tags
                  group by tt.tool_id
               )
             )
         and active = 1`

Error(878,7): PL/SQL: SQL Statement ignored
Error(910,30): PL/SQL: ORA-00920: invalid relational operator

`case when l_is_array then 1 else 0 end,`

Both errors seems to with referencing a boolean in SQL. I was able to fix the compilation error, but not sure what the correct fix is.
